baseURL: "https://gabrielpatron.github.io" 
title: Gabriel D. Patr贸n
paginate: 20
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true

taxonomies:
    tag: tags

menu:
    main:
        - name: Books
          url: books/
          weight: 5 
        - name: Papers
          url: papers/
          weight: 2
        - name: Courses
          url: courses/
          weight: 3
        - name: Data
          url: data/
          weight: 4 
        - name: Blog
          url: https://en.wikipedia.org/wiki/Moritz-Maria_von_Igelfeld_(character)
          weight: 6

params:
    description: "I am a Professor of Philology at the Institute of Romance Philology in Regensburg, Germany. My research focuses mostly on Portuguese irregular verbs."
    author: Gabriel D. Patr贸n
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: ["books","courses","papers","data"]
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Gabriel D. Patr贸n
          subtitle: "I am a Postdoctoral fellow at the Department of Chemical Engineering, University of Waterloo. \n\n\n\n\n\n My research focuses on theory, algorithms, and applications of control and optimization in process systems."
          imageUrl: "PAT_1839-2.JPG"
          imageWidth: 160
          imageHeight: 160
          imageTitle: Moritz-Maria von Igelfeld
          buttons:
            - name: Papers
              url: papers/
            - name: Courses
              url: courses/
            - name: Data
              url: data/

    socialIcons:
        - name: CV
          url: CV_GDP.pdf
        - name: Email
          url: mailto:g2patron@uwaterloo.ca
        - name: Location
          url: location/
        - name: Google Scholar
          url: https://scholar.google.co.uk/citations?user=r1Rw2nQAAAAJ&hl=en

    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Gabriel D. Patr贸n"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2
